### PR TITLE
Always choose the production image as the recommended version

### PR DESCRIPTION
**Pull request by Page-**
Change-type: patch

### CODE REVIEW

File: lib/models/os.coffee [hunk 1]
```diff
@@ -54,8 +54,10 @@ getOsModel = (deps, opts) ->
 			{ versions, latest } = body
 			[ validVersions, invalidVersions ] = partition(versions, semver.valid)
 
-			validVersions.sort(osVersionRCompare)
-			recommended = reject(validVersions, semver.prerelease)?[0] || null
+			potentialRecommendedVersions = reject versions, (version) ->
+				semver.prerelease(version) or _.includes(version, '.dev')
+			potentialRecommendedVersions.sort(osVersionRCompare)
+			recommended = potentialRecommendedVersions?[0] || null
```
Comment (emirotin) [inline lib/models/os.coffee]: Should we recommend the newest .dev version if all the versions are dev?

**Comment by emirotin** [comment]
Windows tests failed with buildUrl(...).then is not a function. Any idea why?

**Comment by Page-** [comment]
I've got no idea on that error, I can't see why this PR would affect it (and definitely not windows-only)

File: lib/models/os.coffee (hunk 1 above)
Comment (Page-) [inline lib/models/os.coffee]: Maybe, but that shouldn't ever be the case - how would you suggest doing it?

**Comment by Page-** [comment]
It looks like the tests were broken by https://github.com/resin-io/resin-sdk/pull/324 @pimterry, as that PR failed with the same message as this when I retried it in https://ci.appveyor.com/project/resin-io/resin-sdk/build/1.0.1150/job/n961n0qw6yaopuy6

**Comment by pimterry** [comment]
That PR is only changed Travis's config, so I can't believe it's the cause of Appveyor's failures. I'll take a closer look now though.

**Comment by Page-** [comment]
You're right, when I initially looked I didn't see an appveyor.yml and thought it must be because it was defaulting to travis.yml, but it looks like something else has changed - actually I just checked and I'm pretty sure it's got to be due to coffee-script 1.12.5: http://coffeescript.org/#changelog

**Comment by pimterry** [comment]
Eugh, ok, that makes sense. Explains why Travis passes too - it's using the yarn-locked versions.

(As an aside, I'd really like to make these consistent, and preferably find a way to ensure dependencies don't shift under the feet of downstream users either. Might be worth looking at shrinkwrap again. Issue: https://github.com/resin-io/resin-sdk/issues/326)

File: lib/models/os.coffee [hunk 2]
```diff
@@ -54,8 +54,10 @@ getOsModel = (deps, opts) ->
 			{ versions, latest } = body
 			[ validVersions, invalidVersions ] = partition(versions, semver.valid)
 
-			validVersions.sort(osVersionRCompare)
```
Comment (pimterry) [inline lib/models/os.coffee]: This no longer sorts the versions list, so the version list shown downstream won't be sorted at all. That definitely needs to stay I think.

Comment (pimterry) [inline lib/models/os.coffee]: This also highlights that we don't have any tests for this code... If you'd like to add some that'd be wonderful, or you're welcome to just file an issue instead and I'll take a look at it soon.

Comment (Page-) [inline lib/models/os.coffee]: You're right - I'll fix this, was just trying to avoid the sort thinking we didn't need it

File: lib/models/os.coffee (hunk 1 above)
Comment (emirotin) [inline lib/models/os.coffee]:
```
releaseVersions = reject versions, (version) ->
  semver.prerelease(version)
prodVersions = reject releaseVersions, (version) ->
  semver.prerelease(version) or _.includes(version, '.dev')
potentialRecommendedVersions = if prodVersions.length then prodVersions else releaseVersions
```

But I don't insist this is required

**Comment by Page-** [comment]
Ok, I've added a test for the sorting @pimterry and as part of it I had to make the sorting be consistent - I think these changes need to be copied into the ui for the host update code though (although it might be worth taking the opportunity to deduplicate)

**Comment by emirotin** [comment]
The HUP code is very similar but slightly different, thus the duplication

**Comment by pimterry** [comment]
@Page- This actually breaks the tests - we've got some tests for the sorting logic itself here: https://github.com/resin-io/resin-sdk/blob/master/tests/util.spec.coffee#L156. Those need updating with this new change.

The travis build not failing from those is a bug that actually did come from that Travis PR, I've got a fix up at https://github.com/resin-io/resin-sdk/pull/328. Should be a quick review and merge there, and then we can rebase this on top to check this is all working correctly..

**Comment by Page-** [comment]
Ok, I'll fix those @pimterry

**Comment by Page-** [comment]
@pimterry I was able to fix it, and it was painfully hard to find :(  Apparently I put the `require` for `osVersionRCompare` in the nodejs only branch by accident, so it wasn't there in the browser env

**Comment by pimterry** [comment]
Once you merge this, it'd be really useful if you could test the auto publish code too. Just push a tagged commit to master which adds the version number to package.json and the changelog, and it should get automatically picked up, built, and pushed to npm. Once I'm sure that's working versionbot can take over that step too, but I'd rather do it by hand until we've seen it all working happily at least once!

**Comment by Page-** [comment]
I pushed a tagged commit @pimterry
